name: CI-CKAN-2.8

on:
  push:
    branches:
      - "ckan-2.8"
  pull_request:
    branches:
      - "ckan-2.8"

env:
  CKANVERSION: 2.8
      
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install flake8
        run: |
          python -m pip install pip==20.3.3
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude ckan,ckanext-saml2auth

  test:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:10
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      ckan-solr:
        # Workflow level env variables are not addressable on job level, only on steps level
        # image: ghcr.io/keitaroinc/ckan-solr-dev:{{ env.CKANVERSION }}
        image: ghcr.io/keitaroinc/ckan-solr-dev:2.8
        ports:
          - 8983:8983

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install nosetests
        run: |
          python -m pip install pip==20.3.3
          pip install nose

      - name: Setup CKAN
        env:
          PGPASSWORD: postgres
        run: |
          bash bin/setup-ckan.bash

      - name: Test
        run: |
          nosetests --ckan --with-pylons=subdir/test.ini --with-coverage --cover-package=ckanext ckanext/saml2auth/tests

      - name: Coveralls
          uses: AndreMiras/coveralls-python-action@develop
